/**
 * The four fields a supplier has, shared by the create route and the edit one.
 *
 * One component rather than two copies because the two forms are genuinely the
 * same form — `POST /supplier` and `PATCH /supplier/{id}` take the same keys,
 * and the only difference between them is that `nama` is the sole required
 * one and that `PATCH` treats an absent key as "leave it alone".
 *
 * `kode` is not one of these fields: it is generated by the backend rather
 * than typed, so this form never sends it and never shows it.
 *
 * The fields are the guide's inverted kind: a small semibold grey label over a
 * bold value on a hairline underline, no box. That is what makes a filled form
 * read as a summary — a boxed field weighs every row the same whether it holds
 * anything or not.
 */
import { StyleSheet, View } from 'react-native';

import { RamahField } from '@/components/shell/ramah';
import { RamahLayout as L } from '@/constants/theme-ramah';

export interface PemasokValues {
  nama: string;
  telepon: string;
  alamat: string;
  npwp: string;
}

export const EMPTY_PEMASOK: PemasokValues = {
  nama: '',
  telepon: '',
  alamat: '',
  npwp: '',
};

/**
 * Trims and turns an empty optional into `null`.
 *
 * `null` and `''` are not the same thing to this contract: `PATCH` documents
 * `null` as *clear the column*, and an empty string would be stored as an empty
 * string.
 */
export function pemasokBody(v: PemasokValues) {
  const kosong = (s: string) => (s.trim() === '' ? null : s.trim());
  return {
    nama: v.nama.trim(),
    telepon: kosong(v.telepon),
    alamat: kosong(v.alamat),
    npwp: kosong(v.npwp),
  };
}

/** The one rule that can refuse a save, checked before spending a request on it. */
export function pemasokError(v: PemasokValues): string {
  if (v.nama.trim() === '') return 'Nama pemasok wajib diisi.';
  return '';
}

export function PemasokFields({
  values,
  onChange,
  autoFocus = false,
}: {
  values: PemasokValues;
  onChange: (patch: Partial<PemasokValues>) => void;
  autoFocus?: boolean;
}) {
  return (
    <View style={styles.fields}>
      <RamahField
        label="Nama pemasok"
        required
        value={values.nama}
        onChangeText={(nama) => onChange({ nama })}
        placeholder="PT Sumber Makmur"
        autoCapitalize="words"
        autoFocus={autoFocus}
        maxLength={255}
      />
      <RamahField
        label="Telepon"
        value={values.telepon}
        onChangeText={(telepon) => onChange({ telepon })}
        placeholder="0812 3456 7890"
        keyboardType="default"
        maxLength={32}
      />
      <RamahField
        label="Alamat"
        value={values.alamat}
        onChangeText={(alamat) => onChange({ alamat })}
        placeholder="Jl. Merdeka 12, Bandung"
        autoCapitalize="sentences"
        multiline
        maxLength={1000}
      />
      <RamahField
        label="NPWP"
        value={values.npwp}
        onChangeText={(npwp) => onChange({ npwp })}
        placeholder="00.000.000.0-000.000"
        keyboardType="default"
        maxLength={32}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  fields: { gap: L.space5 },
});
