/**
 * The one field a unit kerja has, shared by the create route and the edit
 * one — the same split `PemasokFields` makes and for the same reason:
 * `POST /unit-kerja` and `PATCH /unit-kerja/{id}` take the same key.
 *
 * `kode` is not a field here: it is generated by the backend rather than
 * typed, so this form never sends it and never shows it.
 *
 * `is_aktif` is deliberately not a field here either. Deactivating a unit
 * kerja drops every grant that names it out of its holders' `grants` on their
 * next login, which is a consequence worth its own confirmation rather than a
 * toggle buried in a form — `app/pengaturan/[id]/index.tsx` is where that
 * lives, next to the archive icon every other section uses for the same kind
 * of retire.
 */
import { StyleSheet, View } from 'react-native';

import { RamahField } from '@/components/shell/ramah';
import { RamahLayout as L } from '@/constants/theme-ramah';

export interface UnitKerjaValues {
  nama: string;
}

export const EMPTY_UNIT_KERJA: UnitKerjaValues = { nama: '' };

export function unitKerjaBody(v: UnitKerjaValues) {
  return {
    nama: v.nama.trim(),
  };
}

export function unitKerjaError(v: UnitKerjaValues): string {
  if (v.nama.trim() === '') return 'Nama unit kerja wajib diisi.';
  return '';
}

export function UnitKerjaFields({
  values,
  onChange,
  autoFocus = false,
}: {
  values: UnitKerjaValues;
  onChange: (patch: Partial<UnitKerjaValues>) => void;
  autoFocus?: boolean;
}) {
  return (
    <View style={styles.fields}>
      <RamahField
        label="Nama unit kerja"
        required
        value={values.nama}
        onChangeText={(nama) => onChange({ nama })}
        placeholder="Toko Pusat"
        autoCapitalize="words"
        autoFocus={autoFocus}
        maxLength={255}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  fields: { gap: L.space5 },
});
